[setup]
command = "sudo apt update && sudo apt install -y golang-go"

[build]
builder = "nixpacks"


[deploy]
startCommand = "echo starting!"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10